### ISSUE TITLE
Installation questions

### ISSUE THREAD

**Issue by gexda** [geops/bodo#1]
Hello 
Thank you for making bodo public! Great! Maybe you can help me with the following questions:
 

I can't find the declaration of class "Geops_Database_Postgres_Adapter". Where is it? 
I get the following error:

> Fatal error: Class 'Geops_Database_Postgres_Adapter' not found in Pathto_webserver\htdocs\ews\application\Bootstrap.php on line 22

Is there a file missing which needs to be included?

> Warning: include_once(Geops\Database\Postgres\Adapter.php): failed to open stream: No such file or directory in Pathto_webserver\htdocs\ews\library\Zend\Loader.php on line 146

Where are the db parameters meant to be declared? Could you please add some dummy db params to application/configs/application.ini.dist if they should be declared there.

Thank you very much, best regards.

**Comment by friedjoff** [comment]
Geops_Database_Postgres_Adapter is part of an internal library from geOps and not publicly available. Maybe try to replace "Geops_Database_Postgres_Adapter" with "Zend_Db_Adapter_Pdo_Pgsql" in the Bootstraph.php file. 

Database connection parameters need to be configured in application/configs/application.ini (see application.ini.dist for a template).

Let me know if this works for you. We're happy to accept pull requests, but unfortunately this software is not maintained actively anymore.

**Comment by gexda** [comment]
Thank you Friedjoff. That worked for me!
